### ISSUE TITLE
Update the DB and GUI

### ISSUE THREAD

**Issue by itravers** [MarineAppliedResearch/MARP_API#18]
Update the GUI and MARE API STEPS:
1. Create new API & GUI RELEASE.
2. Create Data Backup, and restore that backup to a temp_backup database.
3. Stop production api from running
4. Load New Release Branch on Production API
5. Install new NPM libraries, if needed.
6. Run Migrations, make sure they execute.
7. Check data integrity after migrations.
8. Start Production API.
9. Run through with the new gui versions
10. Distribute new GUI to all workstations.
11. Change gui version number on api.chicosystems.com

**Comment by itravers** [comment]
Step 1 DONE.

now for step 2

**Comment by itravers** [comment]
it looks like the seagate is down?

**Comment by itravers** [comment]
well it looks like this update has completely lost the ability to load videos.

**Comment by itravers** [comment]
tested feature-CloseButtonBug, the error was already introduced.

**Comment by itravers** [comment]
i tried 3.1 on this computer and it's still not working....

but i tried 3.1 on another ocmputer and it seems to be working fine.

going to reset this computer and try again.

**Comment by itravers** [comment]
reset computer and the issue is recurring, the log shows:

ReportErro -_-_- 2023-02-28 12:30:19Z _-_-_- System.InvalidOperationException: Unable to return a TimeSpan property value for a Duration value of 'Automatic'. Check the HasTimeSpan property before requesting the TimeSpan property value from a Duration.
   at System.Windows.Duration.get_TimeSpan()
   at VIDEO_PLAYER.VideoPlayer.updateTimeDisplay(TimeSpan currTime) in C:\Users\eurek\Desktop\Workspace\VIDEO_PROCESSING_GUI\MAREGUI_PROOFofCONCEPT\VideoPlayer.xaml.cs:line 237
   at VIDEO_PLAYER.VideoPlayer.sliProgress_ValueChanged(Object sender, RoutedPropertyChangedEventArgs`1 e) in C:\Users\eurek\Desktop\Workspace\VIDEO_PROCESSING_GUI\MAREGUI_PROOFofCONCEPT\VideoPlayer.xaml.cs:line 393
VIDEOPLAYE -_-_- 2023-02-28 12:30:19Z _-_-_- Unable to return a TimeSpan property value for a Duration value of 'Automatic'. Check the HasTimeSpan property before requesting the TimeSpan property value from a Duration.
ReportErro -_-_- 2023-02-28 12:30:19Z _-_-_- System.InvalidOperationException: Unable to return a TimeSpan property value for a Duration value of 'Automatic'. Check the HasTimeSpan property before requesting the TimeSpan property value from a Duration.

**Comment by itravers** [comment]
lets try to download another 3.1 and see if that works?

**Comment by itravers** [comment]
tried a different 3.1 on my computer, still doesn't work.

Tried the same 3.1 on a different computer, it worked immediatly.

**Comment by itravers** [comment]
i'll try to roll 3.2 and run it on another computer and see if the issue persists.

**Comment by itravers** [comment]
i've tried the new 3.2 on all the other computers and they aren not experiencing this bug, so i updated the gui to 3.2 and i'll figure out my issue later.
