### ISSUE TITLE
Error: No Items loaded when old 60SecondSubstrate Loaded

### ISSUE THREAD

**Issue by itravers** [MarineAppliedResearch/MARP_API#24]
No items are loaded when a current session is attempted to load, found this error:

[2023-10-19 19:22:40.048 UTC] - info: [923281:logger/api.logger.js] Controller: getLastVideoInfo
Executing (default): SELECT max("observation_id") FROM "observations" AS "observations" WHERE "observations"."session_id" = '833';
Executing (default): SELECT "observation_id", "obsID", "PobsID", "project_id", "session_id", "user_id", "tc", "frame", "taxserial", "comname", "count", "sex", "coarsesize", "sizereview", "quadrant", "etc", "taxReview", "note", "downcamera", "timelog", "video_source", "videoLocation", "mediaPosition", "actualPosition", "substrate_bedrock", "substrate_megaclast", "substrate_boulder", "substrate_cobble", "substrate_peddle", "substrate_granule", "substrate_sand", "substrate_mud", "substrate_coral_reef", "substrate_coral_rubble", "substrate_shell_hash", "substrate_shell_rubble", "substrate_algal", "createdAt", "updatedAt" FROM "observations" AS "observations" WHERE "observations"."session_id" = '833' AND "observations"."observation_id" = 57969;
Error
    at Query.run (/home/webserver/mare-api/node_modules/sequelize/lib/dialects/postgres/query.js:50:25)
    at /home/webserver/mare-api/node_modules/sequelize/lib/sequelize.js:314:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PostgresQueryInterface.select (/home/webserver/mare-api/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Function.findAll (/home/webserver/mare-api/node_modules/sequelize/lib/model.js:1134:21)
    at async ObservationRepository.getLastVideoInfo (/home/webserver/mare-api/repository/observation.repository.js:58:40)
    at async ObservationService.getLastVideoInfo (/home/webserver/mare-api/service/observation.service.js:12:16)
    at async ObservationController.getLastVideoInfo (/home/webserver/mare-api/controller/observation.controller.js:14:16) {
  name: 'SequelizeDatabaseError',
  parent: error: column "substrate_peddle" does not exist
      at Parser.parseErrorMessage (/home/webserver/mare-api/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/webserver/mare-api/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/webserver/mare-api/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/webserver/mare-api/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (events.js:314:20)
      at addChunk (_stream_readable.js:297:12)
      at readableAddChunk (_stream_readable.js:272:9)
      at Socket.Readable.push (_stream_readable.js:213:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {

**Comment by itravers** [comment]
It looks like i forgot to chnage the observation model in observation.model.js:

substrate_peddle:{
          type: DataTypes.BOOLEAN,
          defaultValue: false
        },

should be changed to 

substrate_pebble:{
          type: DataTypes.BOOLEAN,
          defaultValue: false
        },

then try again and see if the error persists.

**Comment by itravers** [comment]
Issue Is fixed.
