### ISSUE TITLE
Support For: On Create Fish Window we want to query new api instead of old db

### ISSUE THREAD

**Issue by itravers** [MarineAppliedResearch/MARP_API#7]
On Create Window. We are going to start with creating a new fish window. 

When creating a new fish window, we are going to query for the session that is being created, along with it's associated user, it's associated project and all of it's associated observations.

**Comment by itravers** [comment]
This is a parallel issue with the front end:

https://github.com/MarineAppliedResearch/VIDEO_PROCESSING_GUI/issues/82

**Comment by itravers** [comment]
created

``async getObservationsBySessionID(session_id) {
        try {
            const observations = await this.db.observations.findAll({
                where: {
                    session_id: session_id
                }
            });
            console.log('observations:::', observations);
            return observations;
        } catch (err) {
            console.log(err);
            return [];
        }
    }``

and related structural things

**Comment by itravers** [comment]
Okay, now that we've done that we can go back to

https://github.com/MarineAppliedResearch/VIDEO_PROCESSING_GUI/issues/82

and try to parse the info that gets returned, and see if we can wire it up.

**Comment by itravers** [comment]
Okay, we have the data input window on the front end showing and giving us data from teh backend

https://github.com/MarineAppliedResearch/VIDEO_PROCESSING_GUI/issues/82

**Comment by itravers** [comment]
It looks like our backend db observation model doesn't have sex in it, and when i try to edit that in the gui everything errors out.

**Comment by itravers** [comment]
now coarse size causes us to crash the same way sex did. I bet it's the same issue.

**Comment by itravers** [comment]
okay, we added coarse size, and size review to the db, but now it's still not updating correctly.

**Comment by itravers** [comment]
We are getting "invalid syntax for type integer" which probably means we added " to our json construction when we shouldn't have.....?

**Comment by itravers** [comment]
Inserting  a new observation is not working, because it tries to fill in an observation_id that has already been filled in.

We need to write a backend funciton to query what the max observation_id is, increment it by 1 and add that to our observation before we try to create it.

**Comment by itravers** [comment]
okay, so nowo some of the createFishREcord works, and some of them don't

getting this error on backend:

SyntaxError: Unexpected token U in JSON at position 360
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
SyntaxError: Unexpected token U in JSON at position 363
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
SyntaxError: Unexpected token U in JSON at position 359
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
SyntaxError: Unexpected token U in JSON at position 428
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
SyntaxError: Unexpected token U in JSON at position 360
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
SyntaxError: Unexpected token U in JSON at position 363
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
SyntaxError: Unexpected token U in JSON at position 348
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
SyntaxError: Unexpected token U in JSON at position 348
    at JSON.parse (<anonymous>)
    at parse (T:\mare-api\node_modules\body-parser\lib\types\json.js:89:19)
    at T:\mare-api\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (T:\mare-api\node_modules\raw-body\index.js:224:16)
    at done (T:\mare-api\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (T:\mare-api\node_modules\raw-body\index.js:273:7)
    at IncomingMessage.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by itravers** [comment]
okay, as soon as i load the video there is an unexpected token U in JSON

so we need to examine the json building and see whats wrong.

**Comment by itravers** [comment]
the json leaving the frontend is  {"observation": {  "obsID": "13",  "tc": "00:00:04",  "frame": "9",  "taxserial": "999996",  "comname": "YOY",  "count": "1",  "line": "1",  "dive": "1",  "processorName": "Isaac1",  "video_source": "20211115_214450 Fwd.mp4",  "mediaPosition": "00:00:04.3999931",  "actualPosition": "00:00:04.3999931",  "session_id": "12",  "videoLocation": "C:\Users\eurek\Desktop\Workspace\Misc\Video\Dive 169\Forward\20211115_214450 Fwd.mp4"  }}

**Comment by itravers** [comment]
When an observation is added, we have already created a new observation_id that is independent. But we also need to create a new obsID as well that is independent for this individual session.

**Comment by itravers** [comment]
Just addressed issue

https://github.com/MarineAppliedResearch/VIDEO_PROCESSING_GUI/issues/83

**Comment by itravers** [comment]
just addressed issue
https://github.com/MarineAppliedResearch/MARE_API/issues/8

**Comment by itravers** [comment]
Finished issue https://github.com/MarineAppliedResearch/VIDEO_PROCESSING_GUI/issues/84

**Comment by itravers** [comment]
Working on issue https://github.com/MarineAppliedResearch/VIDEO_PROCESSING_GUI/issues/85

**Comment by itravers** [comment]
Changing obsID to an integer on the backend.

**Comment by itravers** [comment]
okay, we changed to integer on the backend, and now the front end is having issues because obsID is no longer a string, will work on this on frontend [#90](https://github.com/MarineAppliedResearch/VIDEO_PROCESSING_GUI/issues/90)
